# index:
#     path: /
#     controller: App\Controller\DefaultController::index
index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/home.html.twig
        _locale: '%locale%'